name: Update Trends Data

on:
  schedule:
    - cron: '0 0 * * *'   # Runs at 00:00 UTC
    - cron: '0 12 * * *'  # Runs at 12:00 UTC
  workflow_dispatch:      # Allows manual triggering

jobs:
  update-trends:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Script
        run: python futbol-trends.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add trends.json
          git commit -m 'Automated update of trends.json' || echo "No changes to commit"
          git push
          Add GitHub Actions to update trends.json
